### ISSUE TITLE
Create React routing base

### ISSUE THREAD

**Issue by Eriknpy** [Eriknpy/CinemaRepositoryServicePattern#1]
### Tasks

- [ ] Use createBrowserRouter
- [ ] Use Navlink instead of link
- [ ] Have a layout
- [ ] Basic css with declared colors
- [ ] Use Outlet at layout
